server:
  port: 8282
---
spring:
  profiles:
    active: dev, dc #detective-comics
  datasource:
    url: jdbc:h2:mem:dc
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
---
spring:
  profiles:
    active: marvel, default
  datasource:
    url: jdbc:h2:mem:marvel
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
#spring:
#  profiles:
#    active: @spring.profiles.active@
