spring:
  output:
    ansi:
      enabled: always

  liquibase:
    change-log: classpath:db/changelog-master.xml
    default-schema:
    drop-first: false
    contexts: default
    enabled: true

  datasource:
    url: ${db.url}
    driver-class-name: org.postgresql.Driver
    username: ${db.userName}
    password: ${db.password}
    hikari:
      connection-test-query: SELECT 1

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDB201Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
server:
  port: 9090